// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2upqgHCNSCwKaSoS0yy0SJi-Cq2ZmmOk',
    appId: '1:491058889560:web:17d7f8c7b69b27a4fe1b2d',
    messagingSenderId: '491058889560',
    projectId: 'chatme-1de8f',
    authDomain: 'chatme-1de8f.firebaseapp.com',
    storageBucket: 'chatme-1de8f.appspot.com',
    measurementId: 'G-0CCQYB9Z8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7ITaoSuKs0dQzQyAU3-Pwxb727K2Vp9w',
    appId: '1:491058889560:android:34d9659a972c40e2fe1b2d',
    messagingSenderId: '491058889560',
    projectId: 'chatme-1de8f',
    storageBucket: 'chatme-1de8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmGg0oW6NrZGz5alnKkpvOB5yZqVHXySA',
    appId: '1:491058889560:ios:50ca38a0098e89f3fe1b2d',
    messagingSenderId: '491058889560',
    projectId: 'chatme-1de8f',
    storageBucket: 'chatme-1de8f.appspot.com',
    iosClientId: '491058889560-9vbn8ife5vhskcqtcevug0s9i8b55fd1.apps.googleusercontent.com',
    iosBundleId: 'com.example.folderStucture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmGg0oW6NrZGz5alnKkpvOB5yZqVHXySA',
    appId: '1:491058889560:ios:eb33cc15f35f3548fe1b2d',
    messagingSenderId: '491058889560',
    projectId: 'chatme-1de8f',
    storageBucket: 'chatme-1de8f.appspot.com',
    iosClientId: '491058889560-3mbd6ofkt4stre1e4nll8gi0hn73b8sf.apps.googleusercontent.com',
    iosBundleId: 'com.example.folderStucture.RunnerTests',
  );
}
